version: '3.7'

services:
  mongo:
    hostname: mongodb-server
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./data/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mongo
      - home_system
      - skynet

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - notes
    networks:
      - skynet

  notes:
    restart: always
    container_name: home_notes
    image: zaytsevdv/home-notes:prod-latest
    ports:
      - "8080:8080"
    networks:
      - skynet

networks:
  mongo:
    driver: bridge
  home_system:
    driver: bridge
  skynet:
    driver: bridge