version: '3.7'

services:
  mongo:
    hostname: mongodb-server
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./data/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mongo
      - home_system
      - skynet

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - notes
    networks:
      - skynet

  eureka:
    image: springcloud/eureka
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - skynet
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/

  notes:
    restart: always
    container_name: home_notes
    image: zaytsevdv/home-notes:dev-latest
    ports:
      - "8080:8080"
    networks:
      - skynet
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
      spring.profiles.active: 'dev-local'
    links:
      - eureka

  notifications:
    restart: always
    container_name: home_notifications
    image: zaytsevdv/home-notifications:dev-latest
    ports:
      - "8081:8081"
    networks:
      - skynet
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
      spring.profiles.active: 'dev-local'
    links:
      - eureka

networks:
  mongo:
    driver: bridge
  home_system:
    driver: bridge
  skynet:
    driver: bridge